start_date: "2023-01-01"
end_date: "2023-01-03"

save_url: True
save_media_type: True
save_color_palette: True
save_filterable_colors: True

generate_combined_image: True

extcolors_tolerance: 32
extcolors_limit: 4